FROM ubuntu:18.04

COPY bashrc /root/.bashrc

RUN apt-get update

RUN apt-get -qq install \
  build-essential \
  clang \
  cmake

RUN update-alternatives --set c++ /usr/bin/clang++

CMD ["/bin/bash"]

